AMPIRE/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('', include("residency.urls")),
    path('sirk/', include("sirk.urls")),
    path('admin/', include("admins.urls")),
    path('login', auth_views.LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # path('admin/', admin.site.urls),
]

residency/urls.py
from django.urls import path

from . import views

app_name = "residency"

urlpatterns = [
    path('', views.render_residency, name='index'),
    path('current_time', views.get_current_time, name='current_time'),
    path('run', views.run, name='run'),
]

sirk/urls.py
from django.urls import path

from . import views
from .task import compute_sirk

app_name = "sirk"

urlpatterns = [
    path('', views.render_issues, name='render_issues'),
    path('online_sirk_points', views.render_online_sirk_points, name='render_online_sirk_points'),
    # path('manual_sirk_points', views.render_manual_sirk_points, name='manual_sirk_points'),
    path('create_issue', views.create_issue, name='create_issue'),
    path('edit_issue', views.edit_issue, name='edit_issue'),
    # path('add_online_sirk_point', views.add_online_sirk_point, name='add_online_sirk_point'),
    path('create_online_sirk_points', views.create_online_sirk_points, name='create_online_sirk_points'),
    path('edit_online_sirk_points/<int:online_sirk_points_id>/', views.edit_online_sirk_points, name='edit_online_sirk_points'),
    path('delete_online_sirk_points/<int:online_sirk_points_id>/', views.delete_online_sirk_points, name='delete_online_sirk_points'),
    # path('add_manual_sirk_point', views.add_manual_sirk_point, name='add_manual_sirk_point'),

    path('compute_sirk', views.compute_sirk, name='compute_sirk'),
]

residency/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from django.db.models import F, Max, Case, When, Value, DateTimeField
from django.db.models.functions import Coalesce
from admins.models import Member

# Create your models here.

class Residency(models.Model):
    member = models.ForeignKey(Member, on_delete=models.DO_NOTHING)
    date = models.DateField()
    clock_in = models.TimeField()
    clock_out = models.TimeField(null=True)

    def clocking_in(self):
        self.date = timezone.localtime()
        self.clock_in = timezone.localtime().time()
        self.save()

    def clocking_out(self):
        self.clock_out = timezone.localtime().time()
        self.save()

    def get_daily_records():
        target_date = date.today()
    
        # Query the Residency records for the target date
        records = Residency.objects.filter(date=target_date).select_related('member').annotate(
        latest_update=Coalesce(
            Case(
                When(clock_out__isnull=False, then=F('clock_out')),
                default=F('clock_in'),
                output_field=DateTimeField()
            ),
            F('clock_in'),
            output_field=DateTimeField()
            )
        ).order_by('-latest_update', '-clock_in')
        
        return records

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['member', 'date'], name='unique_member_date'),
        ]

residency/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.utils import timezone

from admins.models import Member
from . models import Residency

# Create your views here.

def render_residency(request):

    daily_records = Residency.get_daily_records()

    return render(request, 'residency/residency.html', { 'daily_records' : daily_records })

def get_current_time(request):
    current_time = timezone.localtime().strftime('%H:%M:%S')
    return JsonResponse({'time': current_time})

def run(request):
    if request.method == 'POST':
        id_num = request.POST.get('input')
        now = timezone.localtime()
        print("test")
        try:
            member = Member.objects.get(id_num=id_num)

            # Use get_or_create to retrieve or create the record in one go
            residency, created = Residency.objects.get_or_create(
                member=member,
                date=now,
                defaults={
                    'clock_in': now,
                }
            )

            if not created:
                print("not created")
                # Update the existing record to set the clock_out time
                residency.clocking_out()
        except Member.DoesNotExist:
            print("Member not found.")
        except Exception as e:
            print(f"An error occurred: {e}")

    return redirect('/')
    

residency/templates/residency/residency.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Tap Tap & Go</title>
    {% load static %}
    {% load custom_filters %}
    <link rel="icon" href="{% static 'admin/img/icon.png' %}" type="image/x-icon" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />

    <style>
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            display: none;
        }

        a:hover {
            cursor: default;
        }

        /* New CSS for the clock-in/clock-out system */
        .header {
            background-color: #4CAF50; /* Primary green background color */
            padding: 20px;
            border-bottom-left-radius: 20px; /* Rounded lower left edge */
            border-bottom-right-radius: 20px; /* Rounded lower right edge */
            position: relative;
        }

        .header img {
            max-width: 200px; /* Adjust the size of the rectangular image */
            display: block;
            margin: 0 auto;
        }

        .logo img {
            max-width: 150px; /* Adjust the size of the circular green logo */
            border-radius: 50%;
            display: block;
            margin: 0 auto;
        }

        .container {
            background-color: white; /* White background for the content container */
            padding: 20px;
            border-radius: 10px;
            margin-top: 20px;
            text-align: center;
            /* width: 80%; */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        }

        .employee-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: flex-start;
        }

        .employee-card {
            border: 1px solid #065e00; /* Green border for employee cards */
            border-radius: 10px;
            margin: 10px;
            padding: 10px;
            text-align: center;
            width: 190px; /* Adjust the width of the employee cards as needed */
        }

        #input {
            width: 80%; /* Make the input almost as long as its container */
            border: 2px solid #4CAF50; /* Green border for the input */
            border-radius: 10px; /* Rounded edges for the input */
            padding: 10px;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo"><img src="{% static 'admin/img/icon.png' %}" alt="APP Logo" /></div>
        <a href="{% url 'login' %}"><img src="{% static 'residency/img/heading.png' %}" alt="Tap Tap & Go" /></a>
        
    </div>

    <div class="container">
        <h1><span id="timePlaceholder"></span></h1>
        <div>
            <!-- Employee ID input will be automatically submitted when changed -->
            <form action="{% url 'residency:run' %}" method="post" id="myForm" name="myForm">
                {% csrf_token %}
                <input type="number" id="input" name="input" onchange="handleInput()" />
            </form>
        </div>
    </div>

    <!-- Employee List -->
    <div class="container">
        <h2>Mga Tao</h2>
        <div class="employee-list">
            <!-- Sample Employee Card (You can loop through your employee data to create cards) -->
            {% for record in daily_records %}
                <div class="employee-card">
                    <h3>{{ record.member.get_name }}</h3>
                    <td>ID: {{ record.member.id_num|mask_id }}</td>
                    <p>{{ record.member.get_position }}</p>
                    <p>Clocked In: {{ record.clock_in }}</p>
                    {% if record.clock_out %}
                    <p>Clocked Out: {{ record.clock_out }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <!-- Add more employee cards as needed -->
        </div>
    </div>
    <script src="{% static 'residency/js/residency.js' %}"></script>
</body>
</html>