AMPIRE/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('', include("residency.urls")),
    path('sirk/', include("sirk.urls")),
    path('admin/', include("admins.urls")),
    path('login', auth_views.LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # path('admin/', admin.site.urls),
]

sirk/urls.py
from django.urls import path

from . import views
from .task import compute_sirk

app_name = "sirk"

urlpatterns = [
    path('', views.render_issues, name='render_issues'),
    path('online_sirk_points', views.render_online_sirk_points, name='render_online_sirk_points'),
    # path('manual_sirk_points', views.render_manual_sirk_points, name='manual_sirk_points'),
    path('create_issue', views.create_issue, name='create_issue'),
    path('edit_issue', views.edit_issue, name='edit_issue'),
    # path('add_online_sirk_point', views.add_online_sirk_point, name='add_online_sirk_point'),
    path('create_online_sirk_points', views.create_online_sirk_points, name='create_online_sirk_points'),
    path('edit_online_sirk_points/<int:online_sirk_points_id>/', views.edit_online_sirk_points, name='edit_online_sirk_points'),
    path('delete_online_sirk_points/<int:online_sirk_points_id>/', views.delete_online_sirk_points, name='delete_online_sirk_points'),
    # path('add_manual_sirk_point', views.add_manual_sirk_point, name='add_manual_sirk_point'),

    path('compute_sirk', views.compute_sirk, name='compute_sirk'),
]

sirk/models.py
from django.db import models
from django.utils import timezone
import datetime

from admins.models import APPInfo, Member

# Create your models here.
class Issue(models.Model):
    name = models.CharField(max_length=20)
    online_start_date = models.DateTimeField()
    online_end_date = models.DateTimeField()
    online_double_pts_end_date = models.DateTimeField()
    # manual_start_date = models.DateTimeField()
    # manual_end_date = models.DateTimeField()
    # manual_double_pts_end_date = models.DateTimeField()
    folder_id = models.CharField(max_length=40, null=True, default=None)
    app_info = models.ForeignKey(APPInfo, on_delete=models.DO_NOTHING)
    parent_folder_id = models.CharField(max_length=40)
    is_complete_online = models.BooleanField(default=False)

    def is_online_ongoing(self) : return self.online_start_date <= timezone.now() <= self.online_end_date
    
    def is_online_over(self) : return timezone.now() > self.online_start_date

    def is_final_online_date(self) : return self.online_end_date.date() + datetime.timedelta(days=1) == timezone.now().date()

class OnlinePoints(models.Model):
    rule = models.CharField(max_length=40)
    value = models.IntegerField()
    is_active = models.BooleanField(default=True)

# class SirkRecords(models.Model):
#     issue = models.ForeignKey(Issue, on_delete=models.DO_NOTHING)
#     member = models.ForeignKey(Member, on_delete=models.DO_NOTHING)
#     value = models.IntegerField()

sirk/forms.py
from django import forms

from .models import Issue, OnlinePoints

class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['name', 'online_start_date', 'online_end_date', 'online_double_pts_end_date']
        widgets = {
            'online_start_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local', 
                'class': 'form-control'
            }),
            'online_end_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local', 
                'class': 'form-control'
            }),
            'online_double_pts_end_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local', 
                'class': 'form-control'
            }),
        }

class EditIssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['online_start_date', 'online_end_date', 'online_double_pts_end_date']
        widgets = {
            'online_start_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local', 
                'class': 'form-control'
            }),
            'online_end_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local', 
                'class': 'form-control'
            }),
            'online_double_pts_end_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local', 
                'class': 'form-control'
            }),
        }

class OnlinePointsForm(forms.ModelForm):
    class Meta:
        model = OnlinePoints
        fields = ['rule', 'value']
        widgets = {
            'rule': forms.TextInput(attrs={'class': 'form-control'}),
            'value': forms.NumberInput(attrs={'class': 'form-control', 'min': '1'}),
        }

class EditOnlinePointsForm(forms.ModelForm):
    class Meta:
        model = OnlinePoints
        fields = ['value']
        widgets = {
            'value': forms.NumberInput(attrs={'class': 'form-control'}),
        }

sirk/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from gsheets.sheets import get_sheet_names
from .task import create_folders

from admins.models import APPInfo, Section, Member
from .models import Issue, OnlinePoints

from .forms import IssueForm, EditIssueForm, OnlinePointsForm, EditOnlinePointsForm

# Create your views here.

@login_required
def render_online_sirk_points(request):
    online_points = OnlinePoints.objects.filter(is_active=True)
    edit_forms = {point.pk: EditOnlinePointsForm(instance=point) for point in online_points}
    zipped_points_forms = zip(online_points, [edit_forms[point.pk] for point in online_points])

    return render(request, 'sirk/online_sirk_points.html', {
        'online_points': online_points, 
        'form': OnlinePointsForm(),
        'zipped_points_forms': zipped_points_forms,
        'edit_forms': edit_forms,
    })

def create_online_sirk_points(request):
    if request.method == 'POST':
        form = OnlinePointsForm(request.POST)
        if form.is_valid() : form.save()

    return redirect('sirk:render_online_sirk_points')

def edit_online_sirk_points(request, online_sirk_points_id):
    if request.method == 'POST':
        online_point = get_object_or_404(OnlinePoints, pk=online_sirk_points_id)
        form = EditOnlinePointsForm(request.POST, instance=online_point)
        if form.is_valid() : form.save()

    return redirect('sirk:render_online_sirk_points')

def delete_online_sirk_points(request, online_sirk_points_id):
    if request.method == 'POST':
        online_point = get_object_or_404(OnlinePoints, pk=online_sirk_points_id)
        online_point.is_active = False
        online_point.save()
    return redirect('sirk:render_online_sirk_points')

@login_required
def render_issues(request):
    app_info = APPInfo.objects.last()
    issues = Issue.objects.filter(app_info=app_info)
    last_issue = issues.last()

    context = {
        'issues': issues,
        'form': IssueForm(),
    }

    if issues:
        context['edit_form'] = EditIssueForm(instance=last_issue)
        context['last_issue_name'] = issues.last().name

    return render(request, 'sirk/issue.html', context)

def edit_issue(request):
    if request.method == "POST":
        issue = Issue.objects.last()
        form = EditIssueForm(request.POST, instance=issue)
        
        if form.is_valid():
            new_online_end_date = form.cleaned_data['online_end_date']

            if new_online_end_date != issue.online_end_date:
                issue.is_complete_online = False

            form.save()
            issue.save()

    return redirect('sirk:render_issues')

def create_issue(request):
    if request.method == 'POST':
        form = IssueForm(request.POST)
        if form.is_valid():
            try:
                sections = Section.objects.filter(is_active=True)
                sections_data = []
                for idx, section in enumerate(sections, start=1):
                    members = Member.objects.filter(section=section, is_active=True).filter(
                        Q(position="Kasapi") | Q(position="Korespondente")
                    )
                    section_data = {
                        'name': f'{str(idx).zfill(2)}. {section.name.upper()}',
                        'members': [member.get_name() for member in members]
                    }
                    sections_data.append(section_data)
                
                # Query online sirk data
                online_sirk_rules = OnlinePoints.objects.filter(is_active=True)
                online_sirk_data = [f'{str(idx).zfill(2)}. {online_sirk_rule.rule.upper()}' for idx, online_sirk_rule in enumerate(online_sirk_rules, start=1)]
                
                app_info = APPInfo.objects.last()
                parent_folder_id = app_info.sirk_folder_id

                # Save the issue form and create an issue instance
                issue = form.save(commit=False)
                issue.folder_id = None  # Set additional fields as needed
                issue.app_info = app_info
                issue.parent_folder_id = parent_folder_id
                issue.save()

                # Start any asynchronous tasks (e.g., Celery tasks)
                # add_isyu_in_sirk_tracker.delay(issue.pk)
                create_folders.delay(
                    issue_id=issue.pk,
                    sections=sections_data, 
                    online_sirk=online_sirk_data,
                    parent_folder_id=parent_folder_id,
                )
            except Exception as e:
                print(f"An error occurred: {e}")
            finally:
                # Perform any necessary cleanup here
                pass
    
    return redirect('sirk:render_issues')

from sirk.task import compute_sirk as compute_sirk_task

def compute_sirk(request):
    compute_sirk_task()
    return redirect('/sirk')

sirk/templates/sirk/issue.html
{% extends "admin/admin-base.html" %}
{% block title %}Mga Isyu{% endblock %}
{% load static %}
{% block css %}
{% endblock %}
{% block content %}
    <div class="d-flex justify-content-end mb-3">
        <button type="button" class="btn btn-success me-2" data-toggle="modal" data-target="#createModal">
            Create New Isyu
        </button>
        {% if last_issue_name %}
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal">
            Edit {{ last_issue_name }} Isyu
        </button>
        {% endif %}
    </div>

    {% if issues %}
    <div class="ampire-table table-responsive">
        <h2>Mga Isyu</h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Issue</th>
                    <th scope="col">Online Start Date</th>
                    <th scope="col">Online Double Pts End Date</th>
                    <th scope="col">Online End Date</th>
                </tr>
            </thead>
            <tbody>
                {% for issue in issues %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ issue.name }}</td>
                    <td>{{ issue.online_start_date }}</td>
                    <td>{{ issue.online_double_pts_end_date }}</td>
                    <td>{{ issue.online_end_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

    {% if last_issue_name %}
    <!-- Edit Issue Modal -->
    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Edit {{ last_issue_name }} Isyu</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'sirk:edit_issue' %}" method="post">
                        {% csrf_token %}
                        {{ edit_form.as_p }}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Create Issue Modal -->
    <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createModalLabel">Create New Isyu</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'sirk:create_issue' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Create Issue</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

sirk/templates/sirk/online_sirk_points.html
{% extends "admin/admin-base.html" %}
{% block title %}Online Sirk Points{% endblock %}
{% load static %}
{% block css %}
{% endblock %}
{% block content %}
    <div class="d-flex justify-content-end mb-3">
        <button type="button" class="btn btn-success me-2" data-toggle="modal" data-target="#createModal">
            Create New Online Sirk Points
        </button>
    </div>
    <div class="ampire-table">
        <h2>Online Sirk Points</h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Rules</th>
                    <th scope="col">Points per Image</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for online_point, edit_form in zipped_points_forms %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ online_point.rule }}</td>
                    
                    <!-- The form for saving the points per image -->
                    <form action="{% url 'sirk:edit_online_sirk_points' online_point.pk %}" method="post" style="display: flex;">
                        {% csrf_token %}
                        <td>{{ edit_form.value }}</td>
                        <td>
                            <!-- Save Button -->
                            <button type="submit" class="btn btn-primary me-2">
                                Save
                            </button>
                    </form>

                    <!-- The form for deleting the entry -->
                    <form action="{% url 'sirk:delete_online_sirk_points' online_point.pk %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            Delete
                        </button>
                    </form>
                        </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Create Modal -->
    <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createModalLabel">Create New Online Sirk Points</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'sirk:create_online_sirk_points' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
{% endblock %}